### ISSUE TITLE
Booting the BatRack image after heavy rainfalls leads to an error in the scheduling 

### ISSUE THREAD

**Issue by lampep** [Nature40/BatRack#19]
```
Jul 15 09:37:19 mof-batrack-00001 python3[913]: Traceback (most recent call last):
Jul 15 09:37:19 mof-batrack-00001 python3[913]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Jul 15 09:37:19 mof-batrack-00001 python3[913]:     "__main__", mod_spec)
Jul 15 09:37:19 mof-batrack-00001 python3[913]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
Jul 15 09:37:19 mof-batrack-00001 python3[913]:     exec(code, run_globals)
Jul 15 09:37:19 mof-batrack-00001 python3[913]:   File "/home/pi/BatRack/batrack/__main__.py", line 289, in <module>
Jul 15 09:37:19 mof-batrack-00001 python3[913]:     schedule.run_pending()
Jul 15 09:37:19 mof-batrack-00001 python3[913]:   File "/usr/local/lib/python3.7/dist-packages/schedule/__init__.py", line 780, in run_pending
Jul 15 09:37:19 mof-batrack-00001 python3[913]: INFO:batrack.sensors:Found an input: device 1 - UltraMic384K 16bit r0: USB Audio (hw:1,0)
Jul 15 09:37:19 mof-batrack-00001 python3[913]: INFO:root:MQTT connection established (0)
Jul 15 09:37:19 mof-batrack-00001 python3[913]:     default_scheduler.run_pending()
Jul 15 09:37:19 mof-batrack-00001 python3[913]:   File "/usr/local/lib/python3.7/dist-packages/schedule/__init__.py", line 100, in run_pending
Jul 15 09:37:19 mof-batrack-00001 python3[913]: INFO:root:Subscribed to +/radiotracking/matched/cbor
Jul 15 09:37:19 mof-batrack-00001 python3[913]:     self._run_job(job)
Jul 15 09:37:19 mof-batrack-00001 python3[913]:   File "/usr/local/lib/python3.7/dist-packages/schedule/__init__.py", line 172, in _run_job
Jul 15 09:37:19 mof-batrack-00001 python3[913]:     ret = job.run()
Jul 15 09:37:19 mof-batrack-00001 python3[913]:   File "/usr/local/lib/python3.7/dist-packages/schedule/__init__.py", line 661, in run
Jul 15 09:37:19 mof-batrack-00001 python3[913]: INFO:__main__:BatRack [run.1] finished
Jul 15 09:37:20 mof-batrack-00001 python3[913]:     ret = self.job_func()
Jul 15 09:37:20 mof-batrack-00001 python3[913]:   File "/home/pi/BatRack/batrack/__main__.py", line 233, in stop_and_remove
Jul 15 09:37:20 mof-batrack-00001 python3[913]:     instance.stop()
Jul 15 09:37:20 mof-batrack-00001 python3[913]:   File "/home/pi/BatRack/batrack/__main__.py", line 191, in stop
Jul 15 09:37:20 mof-batrack-00001 python3[913]:     [unit.stop() for unit in self._units]
Jul 15 09:37:20 mof-batrack-00001 python3[913]:   File "/home/pi/BatRack/batrack/__main__.py", line 191, in <listcomp>
Jul 15 09:37:20 mof-batrack-00001 python3[913]:     [unit.stop() for unit in self._units]
Jul 15 09:37:20 mof-batrack-00001 python3[913]:   File "/home/pi/BatRack/batrack/sensors.py", line 71, in stop
Jul 15 09:37:20 mof-batrack-00001 python3[913]:     self.join()
Jul 15 09:37:20 mof-batrack-00001 python3[913]:   File "/usr/lib/python3.7/threading.py", line 1027, in join
Jul 15 09:37:20 mof-batrack-00001 python3[913]:     raise RuntimeError("cannot join thread before it is started")
Jul 15 09:37:20 mof-batrack-00001 python3[913]: RuntimeError: cannot join thread before it is started
```

**Comment by lampep** [comment]
additional log messages:
```
Jul 15 09:37:20 mof-batrack-00001 python3[913]: INFO:batrack.sensors:ping 0
Jul 15 09:37:20 mof-batrack-00001 python3[913]: INFO:batrack.sensors:setting AudioAnalysisUnit trigger True: audio, 1 pings. Newest ping by frequency: 31020.0
Jul 15 09:37:20 mof-batrack-00001 python3[913]: INFO:batrack.sensors:creating wav file '/data/mof-batrack-00001/BatRack/2021-07-15T09_37_20.wav'
Jul 15 09:37:20 mof-batrack-00001 python3[913]: INFO:batrack.sensors:Powering light on
Jul 15 09:37:20 mof-batrack-00001 python3[913]: INFO:batrack.sensors:Starting camera recording
Jul 15 09:37:20 mof-batrack-00001 python3[913]: INFO:__main__:System triggered, starting recordings
Jul 15 09:37:21 mof-batrack-00001 python3[913]: INFO:batrack.sensors:houston we had 33 frames
Jul 15 09:37:21 mof-batrack-00001 python3[913]: INFO:batrack.sensors:Found pattern in log
Jul 15 09:37:23 mof-batrack-00001 python3[913]: INFO:batrack.sensors:houston we had 34 frames
Jul 15 09:37:25 mof-batrack-00001 python3[913]: INFO:batrack.sensors:houston we had 17 frames
Jul 15 09:37:27 mof-batrack-00001 python3[913]: INFO:batrack.sensors:houston we had 0 frames
Jul 15 09:37:27 mof-batrack-00001 python3[913]: WARNING:batrack.sensors:houston we have a problem! No frames are arriving...
Jul 15 09:37:27 mof-batrack-00001 python3[913]: WARNING:batrack.sensors:Shutting down to come up well again...
Jul 15 09:37:27 mof-batrack-00001 sudo[1380]:       pi : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/uhubctl -a cycle -p 3 -l 1-1
Jul 15 09:37:27 mof-batrack-00001 sudo[1380]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 15 09:37:29 mof-batrack-00001 python3[913]: Current status for hub 1-1 [0424:9514, USB 2.00, 5 ports, ppps]
Jul 15 09:37:29 mof-batrack-00001 python3[913]:   Port 3: 0101 power connect [0869:0349]
Jul 15 09:37:29 mof-batrack-00001 python3[913]: Sent power off request
Jul 15 09:37:29 mof-batrack-00001 python3[913]: New status for hub 1-1 [0424:9514, USB 2.00, 5 ports, ppps]
Jul 15 09:37:29 mof-batrack-00001 python3[913]:   Port 3: 0000 off
Jul 15 09:37:29 mof-batrack-00001 python3[913]: Current status for hub 1-1 [0424:9514, USB 2.00, 5 ports, ppps]
Jul 15 09:37:29 mof-batrack-00001 python3[913]:   Port 3: 0000 off
Jul 15 09:37:29 mof-batrack-00001 python3[913]: Sent power on request
Jul 15 09:37:29 mof-batrack-00001 python3[913]: New status for hub 1-1 [0424:9514, USB 2.00, 5 ports, ppps]
Jul 15 09:37:29 mof-batrack-00001 python3[913]:   Port 3: 0100 power
Jul 15 09:37:29 mof-batrack-00001 sudo[1380]: pam_unix(sudo:session): session closed for user root
Jul 15 09:37:29 mof-batrack-00001 python3[913]: Expression 'alsa_snd_pcm_drop( stream->capture.pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3046
Jul 15 09:37:29 mof-batrack-00001 python3[913]: INFO:batrack.sensors:AudioAnalysisUnit termination finished
Jul 16 07:59:41 mof-batrack-00001 python3[913]: INFO:__main__:Caught SIGINT, terminating execution...
Jul 16 07:59:41 mof-batrack-00001 python3[913]: INFO:__main__:[SIGINT] stopping instance
Jul 16 07:59:41 mof-batrack-00001 python3[913]: INFO:__main__:Stopping [run.1] and respective sensor instances
Jul 16 07:59:41 mof-batrack-00001 systemd[1]: Stopping Evaluate sensors for active bats and trigger recordings...
Jul 16 07:59:41 mof-batrack-00001 python3[913]: INFO:batrack.sensors:Stopping camera recording
Jul 16 07:59:41 mof-batrack-00001 python3[913]: INFO:batrack.sensors:Powering light off
Jul 16 07:59:41 mof-batrack-00001 python3[913]: INFO:__main__:Finished cleaning [run.1] sensors
Jul 16 07:59:41 mof-batrack-00001 python3[913]: INFO:__main__:[SIGINT] stopped
Jul 16 07:59:42 mof-batrack-00001 python3[913]: WARNING:batrack.sensors:try to fix camera behaviour
Jul 16 07:59:42 mof-batrack-00001 sudo[11268]:       pi : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/reboot
Jul 16 07:59:42 mof-batrack-00001 sudo[11268]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 16 07:59:43 mof-batrack-00001 sudo[11268]: pam_unix(sudo:session): session closed for user root
Jul 16 07:59:43 mof-batrack-00001 systemd[1]: BatRack.service: Main process exited, code=exited, status=1/FAILURE
Jul 16 07:59:43 mof-batrack-00001 systemd[1]: BatRack.service: Failed with result 'exit-code'.
Jul 16 07:59:43 mof-batrack-00001 systemd[1]: Stopped Evaluate sensors for active bats and trigger recordings.
-- Reboot --
Jul 16 08:01:55 mof-batrack-00001 systemd[1]: Started Evaluate sensors for active bats and trigger recordings.
Jul 16 08:02:00 mof-batrack-00001 python3[834]: INFO:__main__:[run.1] running from 21:30 to 23:59:59
Jul 16 08:02:00 mof-batrack-00001 python3[834]: INFO:__main__:[run.2] running from 00:00 to 05:30
Jul 16 08:02:00 mof-batrack-00001 python3[834]: INFO:__main__:starting run scheduling
```

**Comment by jonashoechst** [comment]
Closing, as BatRack is not further developed here.
